// ---- Pixel art sprites -------------------------------------------------------
// Each sprite is a list of 16-char rows. Palette letters map to colors; '.' is
// transparent. Slots 1/2/3 (shirt, hair, pants) can be overridden per-draw so one
// human sprite set covers every crawler; 4/5/6 are automatic darker shades of 1/2/3.
// Characters and monsters get an automatic 1px outline (remastered look).
const withLegs = (base, legs) => base.slice(0, 12).concat(legs, ['................']);
const HUMAN_DOWN = [
  '......2222......',
  '.....222222.....',
  '....22222222....',
  '....2ssssss2....',
  '....2ksssks2....',
  '....5ssssss5....',
  '.....ssssss.....',
  '....1111111.....',
  '...s1111111s....',
  '...s1114111s....',
  '....1444411.....',
  '....3333333.....',
  '....333.333.....',
  '....336.633.....',
  '....kkk.kkk.....',
  '................'];
const HUMAN_UP = [
  '......2222......',
  '.....222222.....',
  '....22222222....',
  '....22222222....',
  '....25222252....',
  '.....555555.....',
  '.....ssssss.....',
  '....1111111.....',
  '...s1111111s....',
  '...s1114111s....',
  '....1444411.....',
  '....3333333.....',
  '....333.333.....',
  '....336.633.....',
  '....kkk.kkk.....',
  '................'];
const HUMAN_SIDE = [
  '......2222......',
  '.....222222.....',
  '....2222222s....',
  '....222sssss....',
  '....225ssks.....',
  '....255sssss....',
  '.....5ssss......',
  '.....11111......',
  '.....11111s.....',
  '.....11411s.....',
  '.....14441......',
  '.....33333......',
  '.....333........',
  '.....3363.......',
  '.....kkkk.......',
  '................'];
const RACCOON_DOWN = [
  '................',
  '..dd.......dd...',
  '.dGdd.....ddGd..',
  '.dddddddddddddd.',
  '.ddGGGGGGGGGGdd.',
  '.dkkwkGGGGkwkkd.',
  '.dkkkkGGGGkkkkd.',
  '..dGGGGkkGGGGd..',
  '...dGGGGGGGGd...',
  '....ddddddd.....',
  '...ddGGGGGGdd...',
  '...ddGGGGGGddkd.',
  '...ddddddddddkdk',
  '...dd.dddd.dd.kd',
  '...kk.kkkk.kk...',
  '................'];
const RACCOON_UP = [
  '................',
  '..dd.......dd...',
  '.dGdd.....ddGd..',
  '.dddddddddddddd.',
  '.dddddddddddddd.',
  '.ddddGddddGdddd.',
  '.dddddddddddddd.',
  '..dddddddddddd..',
  '...dddddddddd...',
  '....ddddddd.....',
  '...dddddddddd...',
  '...ddddddddddkdk',
  '...ddddddddddkdk',
  '...dd.dddd.dd.kd',
  '...kk.kkkk.kk...',
  '................'];
const RACCOON_SIDE = [
  '................',
  '....dd....dd....',
  '...dGdd..ddGd...',
  '...dddddddddd...',
  '...dGGGGGGGGGd..',
  '...dkkwkkGGkkkd.',
  '...dkkkkGGGGGkd.',
  '....dwwGGGGGkk..',
  '.....dGGGGGGd...',
  '...ddddddddddd..',
  '..kddGGGlllGGGd.',
  '.kdkdGGGlllGGGGd',
  '.dkd.ddddddddddd',
  '.k...dd.dd.dd.d.',
  '.....kk.kk.kk.k.',
  '................'];

const Sprites = {
  PAL: {
    k: '#141420', w: '#ffffff', d: '#4a4a5c', l: '#b8b8c8', r: '#d83030', R: '#801818',
    g: '#48c848', e: '#186818', b: '#3868d0', i: '#182858', y: '#f8d838', o: '#f88030',
    p: '#9848c8', n: '#885030', t: '#c89860', s: '#f8c8a0', c: '#48d8e8', m: '#e848c8',
    G: '#a0a0a0', S: '#606070', v: '#78b860', q: '#403020', z: '#ff9ac9',
    1: '#d83030', 2: '#885030', 3: '#3868d0',
  },
  OUTLINE: '#101020',
  defs: {
    // -------- generic human (recolorable), 3 walk frames per facing ------------
    human_down: HUMAN_DOWN,
    human_down_w1: withLegs(HUMAN_DOWN, ['....333.333.....', '....336.kkk.....', '....kkk.........']),
    human_down_w2: withLegs(HUMAN_DOWN, ['....333.333.....', '....kkk.633.....', '........kkk.....']),
    human_up: HUMAN_UP,
    human_up_w1: withLegs(HUMAN_UP, ['....333.333.....', '....336.kkk.....', '....kkk.........']),
    human_up_w2: withLegs(HUMAN_UP, ['....333.333.....', '....kkk.633.....', '........kkk.....']),
    human_side: HUMAN_SIDE,
    human_side_w1: withLegs(HUMAN_SIDE, ['....333.33......', '...33....33.....', '...kk....kk.....']),
    human_side_w2: withLegs(HUMAN_SIDE, ['.....333........', '.....33.kk......', '.....kk.........']),
    // -------- Chancellor Tibbs, a raccoon --------------------------------
    raccoon_down: RACCOON_DOWN,
    raccoon_down_w1: withLegs(RACCOON_DOWN, ['...ddddddddddkdk', '...dd.dddd.kk.kd', '...kk.kkkk......']),
    raccoon_down_w2: withLegs(RACCOON_DOWN, ['...ddddddddddkdk', '...kk.dddd.dd.kd', '......kkkk.kk...']),
    raccoon_up: RACCOON_UP,
    raccoon_up_w1: withLegs(RACCOON_UP, ['...ddddddddddkdk', '...dd.dddd.kk.kd', '...kk.kkkk......']),
    raccoon_up_w2: withLegs(RACCOON_UP, ['...ddddddddddkdk', '...kk.dddd.dd.kd', '......kkkk.kk...']),
    raccoon_side: RACCOON_SIDE,
    raccoon_side_w1: withLegs(RACCOON_SIDE, ['.dkd.ddddddddddd', '.k...dd.kk.dd.k.', '.....kk....kk...']),
    raccoon_side_w2: withLegs(RACCOON_SIDE, ['.dkd.ddddddddddd', '.k...kk.dd.kk.d.', '........kk....k.']),
    // -------- enemies -------------------------------------------------------
    rat: [
      '................',
      '................',
      '..nn........nn..',
      '.nznn......nnzn.',
      '.nnnnnnnnnnnnnn.',
      '.nnknnnnnnnnknn.',
      '..nnnnnnnnnnnn..',
      '...nnnnnnnnnnnn.',
      '..nnnnnnnnnnnnnz',
      '.nnnnnnnnnnnnn.z',
      '.nnnnnnnnnnnn..z',
      '..nnnnnnnnnnn.z.',
      '..nn.nnnn.nnzz..',
      '..kk.kkkk.kk....',
      '................',
      '................'],
    goo: [
      '................',
      '................',
      '................',
      '......gggg......',
      '....gggggggg....',
      '...gggggggggg...',
      '..ggkgggggkggg..',
      '..gggggggggggg..',
      '.ggggggkkgggggg.',
      '.gggggggggggggg.',
      '.gggggggggggggg.',
      '.gvgggggggggvgg.',
      '..gggggggggggg..',
      '...eeeeeeeeee...',
      '................',
      '................'],
    bat: [
      '................',
      '................',
      '................',
      '.pp..........pp.',
      '.ppp...pp...ppp.',
      '.pppp.pppp.pppp.',
      '.ppppppppppppp..',
      '..ppprppppprpp..',
      '...pppppppppp...',
      '....pppkkppp....',
      '.....pppppp.....',
      '......pppp......',
      '.......pp.......',
      '................',
      '................',
      '................'],
    drone: [
      '................',
      '.......cc.......',
      '......cccc......',
      '....llllllll....',
      '...lllllllllll..',
      '..llllkkkkllll..',
      '..lllkkrrkklll..',
      '..lllkkrrkklll..',
      '..llllkkkkllll..',
      '...lllllllllll..',
      '....llllllll....',
      '.....l....l.....',
      '....ll....ll....',
      '................',
      '................',
      '................'],
    golem: [
      '................',
      '....SSSSSSSS....',
      '...SSSSSSSSSS...',
      '...SSkkSSSkkS...',
      '...SSSSSSSSSS...',
      '....SSSSSSSS....',
      '..SSSSSSSSSSSS..',
      '.SSSGGSSSSGGSSS.',
      '.SSSGGSSSSGGSSS.',
      '.SS.SSSSSSSS.SS.',
      '.SS.SSSSSSSS.SS.',
      '....SSSSSSSS....',
      '....SSSS.SSS....',
      '....SSSS.SSS....',
      '...SSSS..SSSS...',
      '................'],
    crab: [
      '................',
      '................',
      '................',
      '.rr..........rr.',
      '.rrr........rrr.',
      '..rr.kk..kk.rr..',
      '..rrrrrrrrrrrr..',
      '.rrrrrrrrrrrrrr.',
      '.rrrrrrrrrrrrrr.',
      '.rrrrrrrrrrrrrr.',
      '..rrrrrrrrrrrr..',
      '.r.r.r....r.r.r.',
      'r..r..r..r..r..r',
      '................',
      '................',
      '................'],
    cart: [
      '................',
      '..l..........l..',
      '..lllllllllll...',
      '..l.l.l.l.l.l...',
      '..l.l.l.l.l.l...',
      '..lllllllllll...',
      '..l.l.l.l.l.l...',
      '..lllllllllll...',
      '..l.l.l.l.l.l...',
      '...lllllllll....',
      '...rr.....rr....',
      '...kk.....kk....',
      '..kkkk...kkkk...',
      '..kkkk...kkkk...',
      '...kk.....kk....',
      '................'],
    goblin: [
      '................',
      '......gggg......',
      '.....gggggg.....',
      '....ggggggggg...',
      '...gggkggkgggg..',
      '....gggggggg....',
      '.....gggggg.....',
      '......wwww......',
      '....gwwwwwwg....',
      '....gwwwwwwg....',
      '.....wwwwww.....',
      '.....qqqqqq.....',
      '.....qq..qq.....',
      '.....qq..qq.....',
      '.....kk..kk.....',
      '................'],
    hound: [
      '................',
      '................',
      '.ee..........ee.',
      '.eee........eee.',
      '.eeeeeeeeeeeeee.',
      '.eereeeeeeeeree.',
      '.eeeeeeeeeeeeee.',
      '..eeeeekkeeeee..',
      '...eeeeeeeeee...',
      '...eeeeeeeeee...',
      '..eeeeeeeeeeeee.',
      '..eeeeeeeeeeeeee',
      '..ee.eeee.ee....',
      '..ee.eeee.ee....',
      '..kk.kkkk.kk....',
      '................'],
    trash: [
      '................',
      '...q........q...',
      '..qqq......qqq..',
      '..qqqqqqqqqqqq..',
      '.qqqqyqqqqqyqqq.',
      '.qqqqqqqqqqqqqq.',
      '.qqqqqqqqqqqqqq.',
      '..qqqqrrrrqqqq..',
      '..qqqqqqqqqqqq..',
      '.qqqqqqqqqqqqqq.',
      '.qqqgqqqqqqgqqq.',
      '.qqqqqqqqqqqqqq.',
      '..qqqqqqqqqqqq..',
      '...qqqqqqqqqq...',
      '................',
      '................'],
    skeleton: [
      '................',
      '......llll......',
      '.....llllll.....',
      '.....lkllkl.....',
      '.....llllll.....',
      '......lkkl......',
      '.......ll.......',
      '....llllllll....',
      '...l.llllll.l...',
      '...l.llllll.l...',
      '...l.llllll.l...',
      '.....llllll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '.....ll..ll.....',
      '................'],
    mimic: [
      '................',
      '................',
      '...nnnnnnnnnn...',
      '..nnnnnnnnnnnn..',
      '..nyyyyyyyyyyn..',
      '..nnnnnnnnnnnn..',
      '..kwwwwwwwwwwk..',
      '..kwkwkwkwkwwk..',
      '..krrrrrrrrrrk..',
      '..kwwkwkwkwkwk..',
      '..nnnnnnnnnnnn..',
      '..nnnnnnnnnnnn..',
      '..nnnnnnnnnnnn..',
      '...nnnnnnnnnn...',
      '................',
      '................'],
    ratking: [
      '......yyyy......',
      '.....y.yy.y.....',
      '..nn.yyyyyy.nn..',
      '.nznn.nnnn.nnzn.',
      '.nnnnnnnnnnnnnn.',
      '.nnrnnnnnnnnrnn.',
      '..nnnnnnnnnnnn..',
      '.nnnnnnkkknnnnn.',
      'nnnnnnnnnnnnnnnn',
      'nnnnnnnnnnnnnnnz',
      'nnnnnnnnnnnnnn.z',
      '.nnnnnnnnnnnnn.z',
      '..nnnnnnnnnnnzz.',
      '..nnn.nnnn.nnz..',
      '..kkk.kkkk.kk...',
      '................'],
    steward: [
      '................',
      '....cccccccc....',
      '...cccccccccc...',
      '...ckkkkkkkkc...',
      '...ckrkkkkrkc...',
      '...ckkkkkkkkc...',
      '...cccccccccc...',
      '.....cccccc.....',
      '..llllllllllll..',
      '.lllllccccllllll',
      '.ll.llccccll.ll.',
      '.ll.llllllll.ll.',
      '....llllllll....',
      '....llll.lll....',
      '....llll.lll....',
      '...kkkk..kkkk...'],
    gladiatron: [
      '.....y....y.....',
      '....yy....yy....',
      '...yyyyyyyyyy...',
      '...yykkkkkkyy...',
      '...ykkrkkrkky...',
      '...yykkkkkkyy...',
      '....yyyyyyyy....',
      '.rr..yyyyyy..rr.',
      '.rrryyyyyyyyrrr.',
      '.rrryyyyyyyyrrr.',
      '.ll.yyyyyyyy.ll.',
      '.ll.yyyyyyyy.ll.',
      '....yyyyyyyy....',
      '....yyyy.yyy....',
      '....yyyy.yyy....',
      '...kkkk..kkkk...'],
    // -------- objects ----------------------------------------------------
    gate: [
      'SSSSSSSSSSSSSSSS',
      'SkkkkkkkkkkkkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkRRkkRRkkRRkkkS',
      'SkkkkkkkkkkkkkkS',
      'SSSSSSSSSSSSSSSS',
      'SSSSSSSSSSSSSSSS'],
    gate_open: [
      'SSSSSSSSSSSSSSSS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'Sk............kS',
      'SSSSSSSSSSSSSSSS',
      'SSSSSSSSSSSSSSSS'],
    door_safe: [
      '.nnnnnnnnnnnnnn.',
      'nnyyyyyyyyyyyynn',
      'nyssssssssssssyn',
      'nysskssssskssnyn',
      'nyssssssssssssyn',
      'nysssskksssssnyn',
      'nyyyyyyyyyyyyyyn',
      'nnnnnnnnnnnnnnnn',
      'nnnnnnnnnnnnnnnn',
      'nnnnnnnnnnnnnnnn',
      'nnnnnnnnnnnyynnn',
      'nnnnnnnnnnnyynnn',
      'nnnnnnnnnnnnnnnn',
      'nnnnnnnnnnnnnnnn',
      'nnnnnnnnnnnnnnnn',
      'nnnnnnnnnnnnnnnn'],
    door_hells: [
      '.RRRRRRRRRRRRRR.',
      'RRooRRooRRooRRRR',
      'RRooRRooRRooRRRR',
      'RRRRRRRRRRRRRRRR',
      'RRkkkkkkkkkkkkRR',
      'RRkyykkyykkyykRR',
      'RRkkkkkkkkkkkkRR',
      'RRRRRRRRRRRRRRRR',
      'RkkkkkkkkkkkkkkR',
      'RkkkkkkkkkkkkkkR',
      'RkkkkkkkkkkyykkR',
      'RkkkkkkkkkkyykkR',
      'RkkkkkkkkkkkkkkR',
      'RkkkkkkkkkkkkkkR',
      'RkkkkkkkkkkkkkkR',
      'RRRRRRRRRRRRRRRR'],
    door_mercy: [
      '.cccccccccccccc.',
      'ccwwccwwccwwcccc',
      'ccwwccwwccwwcccc',
      'cccccccccccccccc',
      'ccbbbbbbbbbbbbcc',
      'ccbwwbbwwbbwwbcc',
      'ccbbbbbbbbbbbbcc',
      'cccccccccccccccc',
      'cbbbbbbbbbbbbbbc',
      'cbbbbbbbbbbbbbbc',
      'cbbbbbbbbbbwwbbc',
      'cbbbbbbbbbbwwbbc',
      'cbbbbbbbbbbbbbbc',
      'cbbbbbbbbbbbbbbc',
      'cbbbbbbbbbbbbbbc',
      'cccccccccccccccc'],
    exit: [
      'SSSSSSSSSSSSSSSS',
      'SkkkkkkkkkkkkkkS',
      'SkggggggggggggkS',
      'SkgkkkkkkkkkkgkS',
      'SkgkkkkkkkkkkgkS',
      'SkggggggggggggkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkyykkS',
      'SkkkkkkkkkkyykkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
      'SSSSSSSSSSSSSSSS'],
    stash: [
      '................',
      '..SSSSSSSSSSSS..',
      '..SllllllllllS..',
      '..SlSSSSSSSSlS..',
      '..SllllllllllS..',
      '..SlSSSSSSSSlS..',
      '..SllllllllllS..',
      '..SlSSSSSSSSlS..',
      '..SllllllllllS..',
      '..SlSSSSyySSlS..',
      '..SllllllllllS..',
      '..SSSSSSSSSSSS..',
      '..kk........kk..',
      '................',
      '................',
      '................'],
    bench: [
      '................',
      '................',
      '....o....SSS....',
      '...ooo...SkS....',
      '....o....SSS....',
      '.nnnnnnnnnnnnnn.',
      '.nttttttttttttn.',
      '.nnnnnnnnnnnnnn.',
      '..nn........nn..',
      '..nn........nn..',
      '..nn........nn..',
      '..nn........nn..',
      '..kk........kk..',
      '................',
      '................',
      '................'],
    bed: [
      '................',
      '.nnnnnnnnnnnnnn.',
      '.nwwwwnbbbbbbbn.',
      '.nwwwwnbbbbbbbn.',
      '.nwwwwnbbbbbbbn.',
      '.nnnnnnbbbbbbbn.',
      '.nbbbbbbbbbbbbn.',
      '.nbbbbbbbbbbbbn.',
      '.nbbbbbbbbbbbbn.',
      '.nbbbbbbbbbbbbn.',
      '.nbbbbbbbbbbbbn.',
      '.nnnnnnnnnnnnnn.',
      '.kk..........kk.',
      '................',
      '................',
      '................'],
    crate: [
      '................',
      '................',
      '..nnnnnnnnnnnn..',
      '..nttttttttttn..',
      '..ntnnnnnnnntn..',
      '..ntntttttntnn..',
      '..ntntnnnntntn..',
      '..ntntnttntntn..',
      '..ntntnnnntntn..',
      '..ntntttttntnn..',
      '..ntnnnnnnnntn..',
      '..nttttttttttn..',
      '..nnnnnnnnnnnn..',
      '................',
      '................',
      '................'],
    vending: [
      '................',
      '..SSSSSSSSSSSS..',
      '..SccccccccccS..',
      '..SckkkkkkkkcS..',
      '..SckrkykokkcS..',
      '..SckkkkkkkkcS..',
      '..SckgkmkckkcS..',
      '..SckkkkkkkkcS..',
      '..SccccccccccS..',
      '..SSSSSkkSSSSS..',
      '..SSSSSSSSSSSS..',
      '..SSSSSSSSSSSS..',
      '..kk........kk..',
      '................',
      '................',
      '................'],
    chest: [
      '................',
      '................',
      '................',
      '...nnnnnnnnnn...',
      '..nqqqqqqqqqqn..',
      '..nqqqqqqqqqqn..',
      '..nnnnnnnnnnnn..',
      '..nyyyyyyyyyyn..',
      '..nqqqqqyyqqqqn.',
      '..nqqqqyyyyqqqn.',
      '..nqqqqqyyqqqqn.',
      '..nqqqqqqqqqqqn.',
      '..nnnnnnnnnnnnn.',
      '................',
      '................',
      '................'],
    chest_open: [
      '................',
      '...nnnnnnnnnn...',
      '..nkkkkkkkkkkn..',
      '..nkkkkkkkkkkn..',
      '..nnnnnnnnnnnn..',
      '................',
      '................',
      '..nnnnnnnnnnnn..',
      '..nqqqqqqqqqqn..',
      '..nqqqqqqqqqqn..',
      '..nqqqqqqqqqqn..',
      '..nqqqqqqqqqqn..',
      '..nnnnnnnnnnnn..',
      '................',
      '................',
      '................'],
    terminal: [
      '................',
      '..SSSSSSSSSSSS..',
      '..SkkkkkkkkkkS..',
      '..SkgggggkkkkS..',
      '..SkkkkkkkkkkS..',
      '..SkggggggkkkS..',
      '..SkkkkkkkkkkS..',
      '..SkgggkkkkkkS..',
      '..SSSSSSSSSSSS..',
      '......SSSS......',
      '......SSSS......',
      '....SSSSSSSS....',
      '....SSSSSSSS....',
      '................',
      '................',
      '................'],
    stairs: [
      'kkkkkkkkkkkkkkkk',
      'kSSSSSSSSSSSSSSk',
      'kSkkkkkkkkkkkkSk',
      'kSkSSSSSSSSSSkSk',
      'kSkSkkkkkkkkSkSk',
      'kSkSkSSSSSSkSkSk',
      'kSkSkSkkkkSkSkSk',
      'kSkSkSkkkkSkSkSk',
      'kSkSkSkkkkSkSkSk',
      'kSkSkSSSSSSkSkSk',
      'kSkSkkkkkkkkSkSk',
      'kSkSSSSSSSSSSkSk',
      'kSkkkkkkkkkkkkSk',
      'kSSSSSSSSSSSSSSk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk'],
    stairs_locked: [
      'kkkkkkkkkkkkkkkk',
      'kRRRRRRRRRRRRRRk',
      'kRkkkkkkkkkkkkRk',
      'kRkRRRRRRRRRRkRk',
      'kRkRkkkkkkkkRkRk',
      'kRkRkRyyyyRkRkRk',
      'kRkRkRyRRyRkRkRk',
      'kRkRkRyyyyRkRkRk',
      'kRkRkRyyyyRkRkRk',
      'kRkRkRRRRRRkRkRk',
      'kRkRkkkkkkkkRkRk',
      'kRkRRRRRRRRRRkRk',
      'kRkkkkkkkkkkkkRk',
      'kRRRRRRRRRRRRRRk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk'],
    shop: [
      '.yyyyyyyyyyyyyy.',
      '.yrrrrrrrrrrrry.',
      '.yrwwwwwwwwwwry.',
      '.yrwkwkkkwkkwry.',
      '.yrwkwkkkwkkwry.',
      '.yrwwwwwwwwwwry.',
      '.yrrrrrrrrrrrry.',
      '.yyyyyyyyyyyyyy.',
      '...n........n...',
      '...n........n...',
      '...n........n...',
      '...n........n...',
      '...n........n...',
      '...n........n...',
      '................',
      '................'],
    pod: [
      '................',
      '.....cccccc.....',
      '....cccccccc....',
      '...cckkkkkkcc...',
      '...ckwwwwwwkc...',
      '...ckwwwwwwkc...',
      '...ckwwwwwwkc...',
      '...ckwwwwwwkc...',
      '...ckwwwwwwkc...',
      '...cckkkkkkcc...',
      '....cccccccc....',
      '....SSSSSSSS....',
      '...SSSSSSSSSS...',
      '................',
      '................',
      '................'],
    lootbox: [
      '................',
      '................',
      '....yyyyyyyy....',
      '...ymmmmmmmmy...',
      '...ymmyyyymmy...',
      '...ymmyyyymmy...',
      '...yyyyyyyyyy...',
      '...ymmyyyymmy...',
      '...ymmyyyymmy...',
      '...ymmyyyymmy...',
      '...ymmyyyymmy...',
      '....yyyyyyyy....',
      '................',
      '................',
      '................',
      '................'],
  },
  cache: new Map(),
  shade(hex, f) {
    const n = parseInt(hex.slice(1), 16); const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    const c = v => ('0' + Math.round(v * f).toString(16)).slice(-2);
    return '#' + c(r) + c(g) + c(b);
  },
  color(ch, pal) {
    if (ch === '4' || ch === '5' || ch === '6') { const slot = String(ch.charCodeAt(0) - 51); const base = (pal && pal[slot]) || this.PAL[slot]; return this.shade(base, 0.62); }
    return (pal && pal[ch]) || this.PAL[ch];
  },
  // Sprites are rasterized into a (w+2)x(h+2) canvas so the outline can sit outside the art.
  build(name, pal, flip, outline) {
    const rows = this.defs[name]; if (!rows) return null;
    const h = rows.length, w = 16;
    const cv = document.createElement('canvas'); cv.width = w + 2; cv.height = h + 2;
    const c = cv.getContext('2d');
    const solid = [];
    for (let y = 0; y < h; y++) {
      const row = rows[y]; solid.push([]);
      for (let x = 0; x < w; x++) {
        const ch = row[flip ? (w - 1 - x) : x];
        const col = (!ch || ch === '.') ? null : this.color(ch, pal);
        solid[y][x] = !!col;
        if (!col) continue;
        c.fillStyle = col; c.fillRect(x + 1, y + 1, 1, 1);
      }
    }
    if (outline) {
      c.fillStyle = this.OUTLINE;
      for (let y = -1; y <= h; y++) for (let x = -1; x <= w; x++) {
        if (y >= 0 && y < h && x >= 0 && x < w && solid[y][x]) continue;
        const near = (yy, xx) => yy >= 0 && yy < h && xx >= 0 && xx < w && solid[yy][xx];
        if (near(y - 1, x) || near(y + 1, x) || near(y, x - 1) || near(y, x + 1)) c.fillRect(x + 1, y + 1, 1, 1);
      }
    }
    return cv;
  },
  get(name, pal, flip, outline) {
    const key = name + '|' + (pal ? JSON.stringify(pal) : '') + '|' + (flip ? 1 : 0) + '|' + (outline ? 1 : 0);
    let cv = this.cache.get(key);
    if (!cv) { cv = this.build(name, pal, flip, outline); if (cv) this.cache.set(key, cv); }
    return cv;
  },
  // draw(ctx, name, x, y, {pal, flip, scale, alpha, outline})  x/y is the 16x16 art origin.
  draw(ctx, name, x, y, o) {
    o = o || {};
    const outline = o.outline !== false;
    const cv = this.get(name, o.pal, o.flip, outline); if (!cv) return;
    const s = o.scale || 1;
    if (o.alpha != null) { ctx.save(); ctx.globalAlpha = o.alpha; }
    ctx.drawImage(cv, Math.round(x) - s, Math.round(y) - s, cv.width * s, cv.height * s);
    if (o.alpha != null) ctx.restore();
  },
  // sprite name for a walker facing dir with walk frame 0..3: returns [name, flip]
  facing(base, dir, frame) {
    const suffix = dir === 'up' ? '_up' : (dir === 'left' || dir === 'right') ? '_side' : '_down';
    const f = frame ? (frame === 1 ? '_w1' : frame === 3 ? '_w2' : '') : '';
    const name = base + suffix + f;
    return [this.defs[name] ? name : base + suffix, dir === 'left'];
  },
};
